name: CI

on:
  workflow_dispatch:

jobs:
  TEST:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          mkdir PRUEBA

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "Download data" --author 'Ignacio Rossi <ignacio.rvm@gmail.com>'
          git push
